version: "3.8"
services:
  app:
    container_name: hris_container
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    volumes:
      - ./:/var/www/app
      - vendor_volume:/var/www/app/vendor
    networks:
      - localNetwork
    extra_hosts:
      - "host.docker.internal:host-gateway"
  mysql:
    container_name: hris_mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hris_db
      MYSQL_USER: hris_user
      MYSQL_PASSWORD: "Ambonpati71!#"
      MYSQL_ROOT_PASSWORD: "Ambonpati71!#"
    ports:
      - "5454:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - localNetwork

  nginx:
    container_name: hris_nginx
    image: nginx:1.19-alpine
    restart: unless-stopped
    ports:
      - "${NGINX_PORT_FORWARD:-8807}:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - localNetwork

networks:
  localNetwork:
    driver: bridge

volumes:
  vendor_volume:
  mysql_data:
